<?php
include '../inc.php';
$sql="insert into dy_ssq(adr) values ('五区13栋') ";
mysql_query($sql);
$sql="insert into dy_ssq(adr) values ('五区14栋') ";
mysql_query($sql);
$sql="insert into dy_ssq(adr) values ('六区') ";
mysql_query($sql);
$sql="insert into dy_ssq(adr) values ('八区') ";
mysql_query($sql);
$sql="insert into dy_ssq(adr) values ('G1') ";
mysql_query($sql);
$sql="insert into dy_ssq(adr) values ('G2') ";
mysql_query($sql);
$sql="insert into dy_ssq(adr) values ('G3') ";
mysql_query($sql);
$sql="insert into dy_ssq(adr) values ('G4') ";
mysql_query($sql);
$sql="insert into dy_ssq(adr) values ('四区') ";
mysql_query($sql);
$sql="insert into dy_ssq(adr) values ('三区1栋') ";
mysql_query($sql);
$sql="insert into dy_ssq(adr) values ('三区2栋') ";
mysql_query($sql);
$sql="insert into dy_ssq(adr) values ('二区1栋') ";
mysql_query($sql);
$sql="insert into dy_ssq(adr) values ('二区2栋') ";
mysql_query($sql);
$sql="insert into dy_ssq(adr) values ('一区') ";
mysql_query($sql);
$sql="insert into dy_ssq(adr) values ('F1') ";
mysql_query($sql);
$sql="insert into dy_ssq(adr) values ('F2') ";
mysql_query($sql);
$sql="insert into dy_ssq(adr) values ('D1一栋') ";
mysql_query($sql);
$sql="insert into dy_ssq(adr) values ('D1二栋') ";
mysql_query($sql);
$sql="insert into dy_ssq(adr) values ('D2') ";
mysql_query($sql);
?>